package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Thursday, March 9, 2023 12:57:01 AM CET
*/

public interface CalcOperations 
{
  float sum (float a, float b);
  float div (float a, float b) throws CalcApp.CalcPackage.DivisionByZero;
  float mul (float a, float b);
  float sub (float a, float b);
  float mod (float a, float b) throws CalcApp.CalcPackage.DivisionByZero;
  float fac (float a);
} // interface CalcOperations
